import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Asap_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navabr";
import Footer from "@/components/shared/footer";
import Upward from "@/components/shared/Upward";
import { Toaster } from "sonner";
import { Providers } from "@/context/providers";
import { FullscreenProvider } from "@/context/FullScreenContext";
import { ActiveButtonProvider } from "@/context/ActiveButtonContext";
import { Suspense } from "react";

const asap_Condensed = Asap_Condensed({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "VixSpike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={asap_Condensed.className}>
        <Suspense
          fallback={<div className="w-full min-h-screen bg-darkBg"></div>}
        >
          <Toaster richColors />
          <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
            <FullscreenProvider>
              <ActiveButtonProvider>
                <div className="dark:bg-darkBg bg-lightbg ">
                  <Navbar />
                  {children}
                  <Upward />
                  <Footer />
                </div>
              </ActiveButtonProvider>
            </FullscreenProvider>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
